default:
  interruptible: true

before_script:
  - echo "Pipeline Source - ${CI_PIPELINE_SOURCE}"
  - git submodule update --init --recursive

stages:
  - build


linux:
  stage: build
  image: ${CI_REGISTRY_IMAGE}/${OS}:${OSVERSION}
  needs: []
  tags:
    - haswell
  parallel:
    matrix:
      - OS: [ "ubuntu" ]
        OSVERSION: [ 'noble' ]

  script:
    - cmake -S . -B build-dir -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - cmake --build build-dir 2>&1 | tee build.log
    - cmake --build build-dir --target install
      # - (cd build-dir; OMP_NUM_THREADS=1 ctest -V)
      # - cat build.log | grep -- \\[-W | sed 's/.*\[//; s/\]//' | sort | uniq -c | sort -nr


