default:
  interruptible: true

before_script:
  - echo "Pipeline Source - ${CI_PIPELINE_SOURCE}"
  - git submodule update --init --recursive

stages:
  - build


linux-gcc:
  stage: build
  image: ${CI_REGISTRY_IMAGE}/${OS}:${OSVERSION}
  needs: []
  tags:
    - haswell
  parallel:
    matrix:
      - OS: [ "ubuntu" ]
        OSVERSION: [ 'noble', 'resolute' ]
        BLAS: ['BLAS_ON', 'BLAS_OFF']
      - OS: [ "ubuntu" ]
        OSVERSION: [ "noble" ]
        BLAS: [ 'BLAS_ON']
        TLAPACK: ["ON"]
  script:
    - export TLAPACK=${TLAPACK:-OFF}
    - export BLAS=${BLAS##BLAS_}
    - cmake -S . -B build-dir -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLPF_BLAS=${BLAS} -DLPF_EXAMPLES_TLAPACK=${TLAPACK}
    - cmake --build build-dir 2>&1 | tee build.log
    - cmake --build build-dir --target install
    - (cd build-dir; OMP_NUM_THREADS=1 ctest -V)
    - cat build.log | (grep -- '\[-W' || true) | sed 's/.*\[//; s/\]//' | sort | uniq -c | sort -nr

linux-clang:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/llvm-compiler/noble:${LLVM_VERSION}
  needs: []
  tags:
    - haswell
  parallel:
    matrix:
      - LLVM_VERSION: [ "20", "21", "22" ]
  script:
    - apt update && apt install -y libblas-dev libblas64-dev liblapack-dev liblapack64-dev
    - cmake -S . -B build-dir -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - cmake --build build-dir 2>&1 | tee build.log
    - cmake --build build-dir --target install
      # - (cd build-dir; OMP_NUM_THREADS=1 ctest -V)
      # - cat build.log | grep -- \\[-W | sed 's/.*\[//; s/\]//' | sort | uniq -c | sort -nr


linux-intel:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/intel-compiler/noble:${INTEL_VERSION}
  needs: []
  tags:
    - haswell
  parallel:
    matrix:
      - INTEL_VERSION: [ "2025" ]
  script:
    - CC=icx FC=ifx cmake -S . -B build-dir -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - cmake --build build-dir 2>&1 | tee build.log
    - cmake --build build-dir --target install
    # - (cd build-dir; OMP_NUM_THREADS=1 ctest -V)

