INCLUDE(CheckSymbolExists)
MACRO(MathExists fname)
    STRING(TOUPPER ${fname} FNAME)
    check_symbol_exists(${fname} "math.h" HAVE_${FNAME})
    if (NOT HAVE_${FNAME})
        MESSAGE(FATAL_ERROR "math function ${fname} required.")
    endif()
ENDMACRO()

MathExists(acosf)
MathExists(acoshf)
MathExists(asinf)
MathExists(asinhf)
MathExists(atanf)
MathExists(atanhf)
MathExists(j0f)
MathExists(j1f)
MathExists(y0f)
MathExists(y1f)
MathExists(ceilf)
MathExists(cosf)
MathExists(coshf)
MathExists(erff)
MathExists(erfcf)
MathExists(expf)
MathExists(floorf)
MathExists(tgammaf)
MathExists(logf)
MathExists(log10f)
MathExists(lgammaf)
MathExists(sinf)
MathExists(sinhf)
MathExists(sqrtf)
MathExists(tanf)
MathExists(tanhf)
MathExists(atan2f)
MathExists(jnf)
MathExists(ynf)
MathExists(hypotf)
MathExists(powf)
MathExists(frexpf)
